import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-telecom-wholesale-interconnect-settlement",
  "engine": "recovery",
  "title": "Telecom Wholesale Interconnect Settlement",
  "shortTitle": "Telecom Wholesale Interconnect Settlement",
  "tagline": "Reconcile wholesale voice traffic, routing, rates, quality credits, and bilateral carrier settlements.",
  "industry": "Telecom Revenue Assurance",
  "buyer": "Telecom carriers and network operators",
  "uiPort": 4723,
  "apiPort": 5723,
  "accent": "#0369a1",
  "currency": "USD",
  "primaryOutcome": "Telecom Wholesale Interconnect Settlement converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect interconnect agreements, CDRs, routes, prefixes, durations, rates, quality, disputes, invoices, and settlements in one accountable workflow. Reconcile wholesale voice traffic, routing, rates, quality credits, and bilateral carrier settlements.",
  "calculation": {
    "actualKey": "receivedAmount",
    "expectedKey": "entitledAmount",
    "actualLabel": "Received or Recognized Amount",
    "expectedLabel": "Contract or Rule-Supported Entitlement",
    "varianceLabel": "Unrecovered supported value",
    "direction": "expected-minus-actual",
    "finding": "Telecom Wholesale Interconnect Settlement evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective agreement, eligibility rules, and accountable parties",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare the correction, recovery, or compliance package",
      "Track counterparty response, approval, cash, and preventive control closure"
    ]
  }
},[
feature("interconnect-agreement-library","TWI01","Interconnect agreement library","Execute interconnect agreement library using interconnect agreements, CDRs, routes, prefixes, durations, rates, quality, disputes, invoices, and settlements.","Produce a governed interconnect agreement library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Carrier / Interconnect Route","text","Carrier / Interconnect Route · Standard Case"],["caseReference","Interconnect agreement library Reference","text","TWI01-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1607500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1945075],["domainDriver","Traffic Type","select","Origination",["Origination","Termination","Transit"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Interconnect agreement library case","Carrier route registry case","CDR ingestion case","Prefix destination mapping case","Billable duration calculation case"]}),
feature("carrier-route-registry","TWI02","Carrier route registry","Execute carrier route registry using interconnect agreements, CDRs, routes, prefixes, durations, rates, quality, disputes, invoices, and settlements.","Produce a governed carrier route registry decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Carrier / Interconnect Route","text","Carrier / Interconnect Route · Standard Case"],["caseReference","Carrier route registry Reference","text","TWI02-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1607500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1945075],["domainDriver","Traffic Type","select","Origination",["Origination","Termination","Transit"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Interconnect agreement library case","Carrier route registry case","CDR ingestion case","Prefix destination mapping case","Billable duration calculation case"]}),
feature("cdr-ingestion","TWI03","CDR ingestion","Execute cdr ingestion using interconnect agreements, CDRs, routes, prefixes, durations, rates, quality, disputes, invoices, and settlements.","Produce a governed cdr ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Carrier / Interconnect Route","text","Carrier / Interconnect Route · Standard Case"],["caseReference","CDR ingestion Reference","text","TWI03-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1607500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1945075],["domainDriver","Traffic Type","select","Origination",["Origination","Termination","Transit"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Interconnect agreement library case","Carrier route registry case","CDR ingestion case","Prefix destination mapping case","Billable duration calculation case"]}),
feature("prefix-destination-mapping","TWI04","Prefix destination mapping","Execute prefix destination mapping using interconnect agreements, CDRs, routes, prefixes, durations, rates, quality, disputes, invoices, and settlements.","Produce a governed prefix destination mapping decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Carrier / Interconnect Route","text","Carrier / Interconnect Route · Standard Case"],["caseReference","Prefix destination mapping Reference","text","TWI04-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1607500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1945075],["domainDriver","Traffic Type","select","Origination",["Origination","Termination","Transit"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Interconnect agreement library case","Carrier route registry case","CDR ingestion case","Prefix destination mapping case","Billable duration calculation case"]}),
feature("billable-duration-calculation","TWI05","Billable duration calculation","Execute billable duration calculation using interconnect agreements, CDRs, routes, prefixes, durations, rates, quality, disputes, invoices, and settlements.","Produce a governed billable duration calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Carrier / Interconnect Route","text","Carrier / Interconnect Route · Standard Case"],["caseReference","Billable duration calculation Reference","text","TWI05-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1607500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1945075],["domainDriver","Traffic Type","select","Origination",["Origination","Termination","Transit"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Interconnect agreement library case","Carrier route registry case","CDR ingestion case","Prefix destination mapping case","Billable duration calculation case"]}),
feature("rate-deck-versioning","TWI06","Rate deck versioning","Execute rate deck versioning using interconnect agreements, CDRs, routes, prefixes, durations, rates, quality, disputes, invoices, and settlements.","Produce a governed rate deck versioning decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Carrier / Interconnect Route","text","Carrier / Interconnect Route · Standard Case"],["caseReference","Rate deck versioning Reference","text","TWI06-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1607500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1945075],["domainDriver","Traffic Type","select","Origination",["Origination","Termination","Transit"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Interconnect agreement library case","Carrier route registry case","CDR ingestion case","Prefix destination mapping case","Billable duration calculation case"]}),
feature("least-cost-route-validation","TWI07","Least-cost route validation","Execute least-cost route validation using interconnect agreements, CDRs, routes, prefixes, durations, rates, quality, disputes, invoices, and settlements.","Produce a governed least-cost route validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Carrier / Interconnect Route","text","Carrier / Interconnect Route · Standard Case"],["caseReference","Least-cost route validation Reference","text","TWI07-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1607500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1945075],["domainDriver","Traffic Type","select","Origination",["Origination","Termination","Transit"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Interconnect agreement library case","Carrier route registry case","CDR ingestion case","Prefix destination mapping case","Billable duration calculation case"]}),
feature("traffic-imbalance-analysis","TWI08","Traffic imbalance analysis","Execute traffic imbalance analysis using interconnect agreements, CDRs, routes, prefixes, durations, rates, quality, disputes, invoices, and settlements.","Produce a governed traffic imbalance analysis decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Carrier / Interconnect Route","text","Carrier / Interconnect Route · Standard Case"],["caseReference","Traffic imbalance analysis Reference","text","TWI08-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1607500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1945075],["domainDriver","Traffic Type","select","Origination",["Origination","Termination","Transit"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Interconnect agreement library case","Carrier route registry case","CDR ingestion case","Prefix destination mapping case","Billable duration calculation case"]}),
feature("quality-sla-credit","TWI09","Quality SLA credit","Execute quality sla credit using interconnect agreements, CDRs, routes, prefixes, durations, rates, quality, disputes, invoices, and settlements.","Produce a governed quality sla credit decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Carrier / Interconnect Route","text","Carrier / Interconnect Route · Standard Case"],["caseReference","Quality SLA credit Reference","text","TWI09-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1607500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1945075],["domainDriver","Traffic Type","select","Origination",["Origination","Termination","Transit"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Interconnect agreement library case","Carrier route registry case","CDR ingestion case","Prefix destination mapping case","Billable duration calculation case"]}),
feature("fraud-traffic-exclusion","TWI10","Fraud traffic exclusion","Execute fraud traffic exclusion using interconnect agreements, CDRs, routes, prefixes, durations, rates, quality, disputes, invoices, and settlements.","Produce a governed fraud traffic exclusion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Carrier / Interconnect Route","text","Carrier / Interconnect Route · Standard Case"],["caseReference","Fraud traffic exclusion Reference","text","TWI10-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1607500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1945075],["domainDriver","Traffic Type","select","Origination",["Origination","Termination","Transit"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Interconnect agreement library case","Carrier route registry case","CDR ingestion case","Prefix destination mapping case","Billable duration calculation case"]}),
feature("invoice-generation","TWI11","Invoice generation","Execute invoice generation using interconnect agreements, CDRs, routes, prefixes, durations, rates, quality, disputes, invoices, and settlements.","Produce a governed invoice generation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Carrier / Interconnect Route","text","Carrier / Interconnect Route · Standard Case"],["caseReference","Invoice generation Reference","text","TWI11-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1607500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1945075],["domainDriver","Traffic Type","select","Origination",["Origination","Termination","Transit"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Interconnect agreement library case","Carrier route registry case","CDR ingestion case","Prefix destination mapping case","Billable duration calculation case"]}),
feature("counterparty-invoice-audit","TWI12","Counterparty invoice audit","Execute counterparty invoice audit using interconnect agreements, CDRs, routes, prefixes, durations, rates, quality, disputes, invoices, and settlements.","Produce a governed counterparty invoice audit decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Carrier / Interconnect Route","text","Carrier / Interconnect Route · Standard Case"],["caseReference","Counterparty invoice audit Reference","text","TWI12-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1607500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1945075],["domainDriver","Traffic Type","select","Origination",["Origination","Termination","Transit"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Interconnect agreement library case","Carrier route registry case","CDR ingestion case","Prefix destination mapping case","Billable duration calculation case"]}),
feature("dispute-workflow","TWI13","Dispute workflow","Execute dispute workflow using interconnect agreements, CDRs, routes, prefixes, durations, rates, quality, disputes, invoices, and settlements.","Produce a governed dispute workflow decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Carrier / Interconnect Route","text","Carrier / Interconnect Route · Standard Case"],["caseReference","Dispute workflow Reference","text","TWI13-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1607500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1945075],["domainDriver","Traffic Type","select","Origination",["Origination","Termination","Transit"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Interconnect agreement library case","Carrier route registry case","CDR ingestion case","Prefix destination mapping case","Billable duration calculation case"]}),
feature("net-settlement-reconciliation","TWI14","Net settlement reconciliation","Execute net settlement reconciliation using interconnect agreements, CDRs, routes, prefixes, durations, rates, quality, disputes, invoices, and settlements.","Produce a governed net settlement reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Carrier / Interconnect Route","text","Carrier / Interconnect Route · Standard Case"],["caseReference","Net settlement reconciliation Reference","text","TWI14-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1607500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1945075],["domainDriver","Traffic Type","select","Origination",["Origination","Termination","Transit"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Interconnect agreement library case","Carrier route registry case","CDR ingestion case","Prefix destination mapping case","Billable duration calculation case"]}),
feature("route-carrier-analytics","TWI15","Route carrier analytics","Execute route carrier analytics using interconnect agreements, CDRs, routes, prefixes, durations, rates, quality, disputes, invoices, and settlements.","Produce a governed route carrier analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Carrier / Interconnect Route","text","Carrier / Interconnect Route · Standard Case"],["caseReference","Route carrier analytics Reference","text","TWI15-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1607500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1945075],["domainDriver","Traffic Type","select","Origination",["Origination","Termination","Transit"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Interconnect agreement library case","Carrier route registry case","CDR ingestion case","Prefix destination mapping case","Billable duration calculation case"]})
]);
